name: Test k5test
on:
  push:
    branches:
    - main
    paths-ignore:
    - CODE_OF_CONDUCT.md
    - K5TEST-LICENSE.txt
    - LICENSE.txt
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - CODE_OF_CONDUCT.md
    - K5TEST-LICENSE.txt
    - LICENSE.txt
    - README.md

  release:
    types:
    - published

  schedule:
  - cron: 0 9 * * *

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Test
      run: |
        echo "::group::Installing Python Requirements"

        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --requirements requirements-dev.txt
        python -m pip install .

        echo "::endgroup::"

        echo "::group::Running Sanity Checks"

        python -m black . --check
        python -m isort . --check-only

        echo "::endgroup::"
      shell: bash

  publish:
    name: publish
    needs:
    - test

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Build sdist and wheel
      script:
        python setup.py bdist_wheel --universal
        python setup.py sdist

    - name: Capture sdist and wheel
      uses: actions/upload-artifact@v2
      with:
        name: k5test
        path: dist/*

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
